name: Build

on:
  push:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-22.04
          - os: macos-10.15
          # - os: windows-2022

    steps:
    - uses: actions/checkout@v2
    - name: Build (Ubuntu)
      if: ${{ matrix.os == 'ubuntu-22.04'}}
      run: |
        sudo apt update
        sudo apt install -y qtbase5-dev qtwebengine5-dev libtbb-dev
        git clone https://github.com/stachenov/quazip.git
        git -C quazip checkout v1.3
        mkdir -p quazip/build
        pushd quazip/build
        cmake ..
        make -j4
        sudo make install
        popd

        mkdir -p SlackLogViewer/build
        cd SlackLogViewer/build
        cmake .. -DCMAKE_BUILD_TYPE=Release
        make -j4
        mkdir SlackLogViewer_ubuntu
        cp -a SlackLogViewer Cache Resources SlackLogViewer_ubuntu/
        touch SlackLogViewer_ubuntu/Cache/.keep
    - name: Build (macOS)
      if: ${{ matrix.os == 'macos-10.15' }}
      run: |
        brew install coreutils qt@5 tbb
        wget https://raw.githubusercontent.com/Homebrew/homebrew-core/e77259102655b0390273bdc01a08c9eb61b934ca/Formula/quazip.rb
        brew install ./quazip.rb
        GCC_VERSION=$(basename $(grealpath $(brew --prefix gcc)))
        GCC_MAJOR_VERSION=${GCC_VERSION%%.*}

        mkdir -p SlackLogViewer/build
        cd SlackLogViewer/build
        MACOSX_DEPLOYMENT_TARGET=10.14 cmake .. -DCMAKE_PREFIX_PATH=$(brew --prefix qt@5) -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_COMPILER=g++-${GCC_MAJOR_VERSION} -DCMAKE_C_COMPILER=gcc-${GCC_MAJOR_VERSION}
        make -j4
        tar -c SlackLogViewer.app Cache Resources | xz -6 > SlackLogViewer_macos.tar.xz
    - name: Build (Win)
      if: ${{ matrix.os == 'windows-2022' }}
      shell: bash
      run: |
        choco install -y qt5-default cmake
        git clone https://github.com/stachenov/quazip.git
        git -C quazip checkout v1.3
        mkdir -p quazip/build
        pushd quazip/build
        cmake ..
        make -j4
        sudo make install
        popd

        mkdir -p SlackLogViewer/build
        cd SlackLogViewer/build
        cmake .. -DCMAKE_BUILD_TYPE=Release
        make -j4
        mkdir SlackLogViewer_win
        cp -a SlackLogViewer Cache Resources SlackLogViewer_win/
        touch SlackLogViewer_win/Cache/.keep
    - name: Upload (Ubuntu)
      if: ${{ matrix.os == 'ubuntu-22.04' }}
      uses: actions/upload-artifact@v2
      with:
        name: ubuntu
        path: SlackLogViewer/build/SlackLogViewer_ubuntu
    - name: Upload (macOS)
      if: ${{ matrix.os == 'macos-10.15' }}
      uses: actions/upload-artifact@v2
      with:
        name: macos
        path: SlackLogViewer/build/SlackLogViewer_macos.tar.xz
    - name: Upload (Win)
      if: ${{ matrix.os == 'windows-2022' }}
      uses: actions/upload-artifact@v2
      with:
        name: win
        path: SlackLogViewer/build/SlackLogViewer_win
