name: windows

on: [ push, pull_request ]

jobs:
  build:
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v2
    - uses: microsoft/setup-msbuild@v1.3.1
    - name: Install Qt
      uses: jurplel/install-qt-action@v3
      with:
        version: '6.2.4'
        target: 'desktop'
        dir: '${{github.workspace}}/qt/'
        modules: qtwebengine qtwebchannel qtpositioning
    - name: Install zlib
      shell: bash
      if: ${{ matrix.os == 'windows-2019' }}
      run: |
        vcpkg install zlib 
    - name: Install QuaZIP
      shell: bash
      env:
        CMAKE_PREFIX_PATH: ${{env.Qt6_Dir}}
      run: |
        mkdir -p quazip_1.4
        cd quazip_1.4
        git clone https://github.com/stachenov/quazip.git
        git -C quazip checkout 9d3aa3ee948c1cde5a9f873ecbc3bb229c1182ee  # v1.3_useQtXZlibInConfigCmake
        mkdir 'build'
        mkdir 'installed'
        cmake -S quazip -B build -DCMAKE_BUILD_TYPE=Release
        cmake --build build
        cmake --install build --prefix installed
        cd ..
    - uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: x64
        sdk: 8.1
    - name: Build
      env:
        CMAKE_PREFIX_PATH: ${{env.Qt6_Dir}};${{github.workspace}}/quazip_1.4/installed
      run: |
        cd SlackLogViewer
        mkdir build
        mkdir SlackLogViewer_windows
        cmake -S ./ -B build -G "Visual Studio 16 2019" -A x64 -DCMAKE_BUILD_TYPE=Release
        cmake --build build
        cmake --install build --prefix SlackLogViewer_windows
    - name: Upload
      uses: actions/upload-artifact@v2
      with:
        name: win
        path: SlackLogViewer/build/SlackLogViewer_win